version: '3.4'

services:
  postgres:
    container_name: kiwi-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kiwi
      - POSTGRES_PASSWORD=kiwi


volumes:
  postgres_data: